name: Build Geode Mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - Win64
          - Android32
          - Android64

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LLVM 19
        shell: bash
        run: |
          wget -q https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19

          echo "/usr/lib/llvm-19/bin" >> "$GITHUB_PATH"

          export PATH="/usr/lib/llvm-19/bin:$PATH"

          echo "clang:"
          which clang
          clang --version

          echo "clang++:"
          which clang++
          clang++ --version

      - name: Build Geode mod
        uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          target: ${{ matrix.target }}
          sdk: given

      - name: Upload .geode
        uses: actions/upload-artifact@v4
        with:
          name: dopustim-${{ matrix.target }}
          path: ${{ steps.build.outputs.build-output }}/*.geode
