name: Build Geode Mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        target:
          - Win64
          - Android32
          - Android64

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Clang 19
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-19 clang++-19 lld-19 llvm-19
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-19 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-19 100
          clang --version
          clang++ --version

      - name: Build Geode mod
        uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          target: ${{ matrix.target }}
          sdk: given

      - name: Upload .geode
        uses: actions/upload-artifact@v4
        with:
          name: dopustim-${{ matrix.target }}
          path: ${{ steps.build.outputs.build-output }}/*.geode
